version: '3.4'

networks:
  k6_network:
  grafana_network:

services:
  influxdb:
    container_name: influxdb_container
    image: influxdb:1.8
    networks:
      - k6_network
      - grafana_network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    container_name: grafana_container
    image: grafana/grafana:latest
    networks:
      - grafana_network
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    # volumes:  
    #   - ./grafana:/etc/grafana/provisioning/

  k6:
    container_name: k6_container
    image: loadimpact/k6:latest
    networks:
      - k6_network
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./samples:/scripts